### ISSUE TITLE
1.61.0 is out

### ISSUE THREAD

**Issue by SamuelMarks** [lasote/conan-boost#11]
http://www.boost.org/users/history/version_1_61_0.html

**Comment by BleuGamer** [comment]
I actually can't get msvc to link with boost on the @lasote/vcpkg. I really want the boost/dll, but I can't get it to work at all. 1.60@lasote/stable works amazing.

**Comment by KindDragon** [comment]
1.62 available too http://www.boost.org/users/history/version_1_62_0.html

**Comment by BleuGamer** [comment]
True, any word on the conan package?

**Comment by lasote** [comment]
Hi guys! Sorry for the delay, too much work. 
I'm pushing `Boost/1.62.0@lasote/testing` right now (will take some time).
I've detected some problems with bzip2 dependency, so I don't know if it will fail too much, CI will tell us.
If it works just fine I will promote it to lasote/stable channel.

**Comment by Croydon** [comment]
@lasote What is the state of 1.62? Travis looks fine, only some timeouts.

**Comment by lasote** [comment]
@Croydon I've not try it, I was waiting for some feedback in the lasote/testing channel before I promote it to stable, so I assume it's ok (or no one tried it LoL) So I'm pushing it to stable.

**Comment by Croydon** [comment]
Done.

**Comment by lasote** [comment]
I created a new recipe for 1.66.0

**Comment by SSE4** [comment]
This issue was moved to conan-community/community#84
