### ISSUE TITLE
Error building boost

### ISSUE THREAD

**Issue by mcraveiro** [lasote/conan-boost#12]
Hi,

Whilst investigating a problem [1], I tried to build the Boost package locally and upload it to my account. I followed the instructions in the readme [2], installing latest conan. However, when I try to build I get:

```
$ python build.py
Traceback (most recent call last):
  File "build.py", line 1, in <module>
    from conan.packager import ConanMultiPackager
ImportError: No module named conan.packager
```

Am I missing a step somewhere such as setting up python's path?

Cheers

Marco

[1] https://github.com/conan-io/conan/issues/138
[2] https://github.com/lasote/conan-boost/blob/master/README.md

**Comment by lasote** [comment]
It's needed to install "conan_package_tools" pip package.

```
pip install conan_package_tools
```

**Comment by mcraveiro** [comment]
Ah excellent. I got a bit further now, but it seems the username is mandatory:

```
$ python build.py
Traceback (most recent call last):
  File "build.py", line 7, in <module>
    builder = ConanMultiPackager()
  File "/home/marco/.local/lib/python2.7/site-packages/conan/packager.py", line 35, in __init__
    raise Exception("Instance ConanMultiPackage with 'username' "
Exception: Instance ConanMultiPackage with 'username' parameter or use CONAN_USERNAME env variable
```

I've solved the problem by setting the environment variable as I couldn't figure out how to supply the parameter:

```
CONAN_USERNAME=mcraveiro python build.py
```

I'll send you a PR to add these steps readme once I get it all working.

Cheers

**Comment by mcraveiro** [comment]
Actually, didn't get very far, now compilation fails due to some missing GCC headers:

```
gcc.compile.c++ bin.v2/libs/thread/build/gcc-5.3.1/dbg/adrs-mdl-32/thrd-mlt/pthread/thread.o
In file included from ./boost/config/compiler/gcc.hpp:152:0,
                 from ./boost/config.hpp:39,
                 from ./boost/thread/detail/config.hpp:11,
                 from libs/thread/src/pthread/thread.cpp:9:
/usr/include/c++/5/cstddef:44:28: fatal error: bits/c++config.h: No such file or directory
compilation terminated.

    "g++"  -ftemplate-depth-128 -O0 -fno-inline -Wall -pedantic -g -march=i686 -pthread -fPIC -m32 -Wextra -Wno-long-long -Wno-unused-parameter -Wunused-function -pedantic -DBOOST_ALL_NO_LIB=1 -DBOOST_ATOMIC_DYN_LINK=1 -DBOOST_SYSTEM_DYN_LINK=1 -DBOOST_THREAD_BUILD_DLL=1 -DBOOST_THREAD_DONT_USE_CHRONO -DBOOST_THREAD_POSIX -D_GLIBCXX_USE_CXX11_ABI=0  -I"." -c -o "bin.v2/libs/thread/build/gcc-5.3.1/dbg/adrs-mdl-32/thrd-mlt/pthread/thread.o" "libs/thread/src/pthread/thread.cpp"
```

Funny thing is I can compile all my code with this compiler and the headers are in the system. It seems the compiler path is somehow not being detected correctly within the conan build environment. Oh well, I'll keep hunting.

**Comment by lasote** [comment]
Yes, the USERNAME is required, You can read more details about conan_package_tools here: https://github.com/conan-io/conan-package-tools

About the compilation error... not a clue. It compiles well in my machine and docker containers with gcc.

**Comment by mcraveiro** [comment]
Ah I see. I was hoping I could just follow the readme and get a working boost. Seems like this requires a bit of fiddling on my side, so I'll give it a raincheck then. Thanks for the help.
