### ISSUE TITLE
Error on building with mingw

### ISSUE THREAD

**Issue by dlarudgus20** [lasote/conan-boost#14]
Error occurs when trying to build with mingw. Here's the error message in my case.

> **\>conan install Boost/1.60.0@lasote/stable --building=missing**
> (...)
> **Boost/1.60.0@lasote/stable:** Generated txt created conanbuildinfo.txt
> Building Boost.Build engine
> 'cl' is not recognized as an internal or external command,
> operable program or batch file.
> 
> Failed to build Boost.Build engine.
> Please consult bootstrap.log for further diagnostics.
> 
> You can try to obtain a prebuilt binary from
> 
>    http://sf.net/project/showfiles.php?group_id=7586&package_id=72941
> 
> Also, you can file an issue at http://svn.boost.org
> Please attach bootstrap.log in that case.
> **Boost/1.60.0@lasote/stable:** WARN: cd boost_1_60_0 && b2 toolset=gcc link=static
> variant=release address-model=32 define=_GLIBCXX_USE_CXX11_ABI=1  -j4 --abbrevia
> te-paths --without-python
> 'b2' is not recognized as an internal or external command,
> operable program or batch file.
> 
> **Boost/1.60.0@lasote/stable:** ERROR: Package '7167fd2e0ba75a217cdebd50ea03b41266bc
> 7970' build failed
> **Boost/1.60.0@lasote/stable:** WARN: Build folder D:\ConanData\Boost\1.60.0\lasote\
> stable\build\7167fd2e0ba75a217cdebd50ea03b41266bc7970
> ERROR: Boost: Error 1 while executing cd boost_1_60_0 && b2 toolset=gcc link=sta
> tic variant=release address-model=32 define=_GLIBCXX_USE_CXX11_ABI=1  -j4 --abbr
> eviate-paths --without-python

I assume that the next code in part of `conanfile.py` is the reason.

```
    def build(self):
        if self.options.header_only:
            self.output.warn("Header only package, skipping build")
            return
        command = "bootstrap" if self.settings.os == "Windows" else "./bootstrap.sh"
```

It should be `"bootstrap mingw"` when we build with mingw.

**Comment by lasote** [comment]
Hi, thanks for telling. I've updated the recipe. Please run conan install command again with the **"-u"** option to update the recipe and tell me if now it works!

**Comment by dlarudgus20** [comment]
Oh, [the updated recipe](https://github.com/lasote/conan-boost/commit/b2304210bf39ec1be14885a700c326b69db30217) is exactly what I did after opne this issue :)
