### ISSUE TITLE
Build breaks on MinGW

### ISSUE THREAD

**Issue by bjoernpollex** [lasote/conan-boost#18]
I've created a package that uses Boost, and [one user][1] saw an error when building with MinGW. A similar issue was described [here][2]. This package is quite complex, and I don't have Windows machine to test it, so I can't do much about it.

[1]: https://github.com/libnonius/nonius/issues/45#issuecomment-170940535
[2]: https://github.com/conan-io/conan/issues/215

**Comment by lasote** [comment]
HI! I tried to compile it (test_package) with mingw and there is no Boost recipe issue, but some compilation problems with the example. The issue you mention was using a very old conan, maybe those problems has been solved in current conan version. If they could try it with conan 0.12.0 would be great. Thanks!
