### ISSUE TITLE
[windows] boost build ignores conan.conf compiler.version

### ISSUE THREAD

**Issue by mi-ael** [lasote/conan-boost#2]
Hi,
I specified VS 14 in my conan.conf, but boost was still built for VS 12 (which led to linker errors)

I tried it on Boost 1.59.0.

conan.conf:
```
[storage]
# This is the default path, but you can write your own
path: G:/conan_data

[remotes]
conan.io: https://server.conan.io
local: http://localhost:9300

[settings_defaults]

arch=x86_64
build_type=Release
compiler=Visual Studio
compiler.runtime=MD
compiler.version=14
os=Windows
```

I guess this is the error: conanfile.py:55
```
        if self.settings.compiler == "Visual Studio":
            flags.append("toolset=msvc-12.0")
```

Once again, thanks for maintaining boost for conan!

**Comment by lasote** [comment]
Hi!
First of all THANK YOU for try it and help us to make this tool! :D We are few people working on conan nowadays (too much work with little time) and your helps give us wings! :dancers: 

I will try to change the flag and will see if it fixes the building.
Only in case you want to try to solve yourself, you can modify the **conanfile.py** and try to build with the modified one:

1. Clone this repository and checkout to the right branch (1.59)
2. Modify the conanfile.py and export it to your user/channel:

     $ conan export miael/testing 

3. Change the requirement in your project to your own channel:

    [requires]
    Boost/1.59.0@miael/testing

4. If you fix the problem would be great if you make a Pull Request to my repository, we will be friends forever! hehehehe. You can always upload the conanfile.py and the generated packages to your own user account if you want! I do not pretend to be the owner of any conan package, would be great in the future if the community do it.

:+1:

**Comment by lasote** [comment]
I uploaded the conanfile.py recipe with the change you notice:

    if self.settings.compiler == "Visual Studio":
            flags.append("toolset=msvc-%s.0" % self.settings.compiler.version)

I generated a package with Visual Studio 14 and works well!!

Remember, if you wan to try to build Boost again, make sure of delete your local copy of Boost (1) or register the new recipe (2).

1. conan remove Boost*
2. git clone git@github.com:lasote/conan-boost.git
    cd conan-boost
    conan export lasote/stable

 I will upload some Visual Studio 14 Boost packages, so maybe you don't need to compile it anymore.

Please, tell me if it works now! :)

**Comment by mi-ael** [comment]
Thanks!
