### ISSUE TITLE
FindBoost Wrapper does not work on Windows - Potential fix attached

### ISSUE THREAD

**Issue by monsdar** [lasote/conan-boost#21]
When using the FindBoost-Wrapper I get the error that unit_test_framework is not found. When instead using the following FindBoost everything gets detected as needed: [FindBoost.cmake](https://gist.github.com/monsdar/e1d10fcfa4548d1406d2d694ea84336d)

**Comment by lasote** [comment]
Could you open a PR to see the differences? thanks!

**Comment by monsdar** [comment]
I created the Pull Request: https://github.com/lasote/conan-boost/pull/24

**Comment by monsdar** [comment]
Seems as if my version of the file is a bit older, you made some more changes since I got the fix. Hope it's possible to sort that out somehow (perhaps it is already solved?).

Sorry for not being able to provide more input - I wasn't the one fixing it in the first place.

**Comment by Croydon** [comment]
I guess this can be closed because of missing feedback and due to the fact that it seem to work for most or even all.
