### ISSUE TITLE
Boost clang 4.0 for linux

### ISSUE THREAD

**Issue by bjadamson** [lasote/conan-boost#31]
Hi there, is it possible for me to build the boost 1.60 library locally? Right now I'm getting linker errors, which makes it seem like there weren't any binaries for my cpu. I've definately added the "--build missing" flag. 

I went to the website and checked, it looks like binaries are uploaded for gcc but not clang. I'm using clang 4.0 with my project, and trying to use the boost library gave me the following linker error:

> /usr/bin/ld: i386 architecture of input file `/home/benjamin/.conan/data/Boost/1.60.0/lasote/stable/package/2f0d2112bdbff61b758b140d2a55cd9e93d9dc86/lib/libboost_filesystem.a(operations.o)' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `/home/benjamin/.conan/data/Boost/1.60.0/lasote/stable/package/2f0d2112bdbff61b758b140d2a55cd9e93d9dc86/lib/libboost_filesystem.a(path.o)' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `/home/benjamin/.conan/data/Boost/1.60.0/lasote/stable/package/2f0d2112bdbff61b758b140d2a55cd9e93d9dc86/lib/libboost_system.a(error_code.o)' is incompatible with i386:x86-64 output
/home/benjamin/.conan/data/Boost/1.60.0/lasote/stable/package/2f0d2112bdbff61b758b140d2a55cd9e93d9dc86/lib/libboost_filesystem.a(operations.o): In function `std::__1::__allocate(unsigned int)':

https://github.com/bjadamson/BoomHS/blob/release/scripts/bootstrap.bash#L73

Locally I've added the commands to pull in the boost libraries during compilation. I figured this would be easier than contacting the package owner, and trying to get them to upload binaries. Thanks!

**Comment by lasote** [comment]
Hi! It seems there is some problem with the architecture, not sure why...  I bet in some point you are mixing x86 with x86_64. Is the error raising in Boost package build or then in linking stage?

**Comment by helmesjo** [comment]
@lasote Do you mind taking a peek [here](https://travis-ci.org/helmesjo/conan-thrift/jobs/400594685) on a similar issue but for [conan-openssl](https://github.com/conan-community/conan-openssl)..?
Happens when building on gcc 6 (also on 5 when I tried locally) with settings:
```
+--------------------+
| Profile            |
|--------------------|
| include(default)   |
|                    |
| [settings]         |
| arch=x86           |
| build_type=Release |
| compiler=gcc       |
| compiler.version=6 |
| [options]          |
| thrift:shared=True |
| [env]              |
|                    |
| [build_requires]   |
+--------------------+
```

Also, could you please enable issues on conan-openssl? :)
