### ISSUE TITLE
Win7 x64 build error -- conan test command layout has changed

### ISSUE THREAD

**Issue by ksmith-mm** [lasote/conan-boost#32]
Not sure if this is a problem with my system or with conan-boost but I am having problems building the libraries on Win7.

 I am only trying to build 1.58.0 at the moment. After it builds the MDd version of Boost, it fails to start the next version. I'm not sure if this is a bug or if it is a configuration issue but I am unable to find any mention of it in the docs and I am unsure where else to ask.

Note: I did modify the build.py to ONLY build 64bit and for VS2013. (I'll link it to the issue)

[conan-boost-build.txt](https://github.com/lasote/conan-boost/files/625634/conan-boost-build.txt)
[conan-build-log.txt](https://github.com/lasote/conan-boost/files/625625/conan-build-log.txt)

```
PROJECT: Generated cmake created conanbuildinfo.cmake
PROJECT: Generated conaninfo.txt
ERROR: ******* conan test command layout has changed *******

In your "test" folder 'conanfile.py' you should use the
path to the conanfile_directory, something like:

    self.run('cmake %s %s' % (self.conanfile_directory, cmake.command_line))


ERROR: ******* conan test command layout has changed *******

In your "test" folder 'CMakeLists.txt' you should use the
path to the CMake binary directory, like this:

   include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)


Project: WARN: conanbuildinfo.txt file not found in E:\playground\conan\conan-boost\test\build\3345cb4bad693ccf44a5e04c946c4f8d6c3179b7
It is recommended for this command
You can generate it using 'conan install -g txt'
Project: WARN: conanenv.txt file not found in E:\playground\conan\conan-boost\test\build\3345cb4bad693ccf44a5e04c946c4f8d6c3179b7
It is recommended for this command
You can generate it using 'conan install -g env'
CMake Error: The source directory "E:/playground/conan/conan-boost/test/build/3345cb4bad693ccf44a5e04c946c4f8d6c3179b7" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ERROR: Error 1 while executing cmake . -G "Visual Studio 12 2013 Win64"  -DCONAN_LINK_RUNTIME=/MDd -DCONAN_COMPILER="Visual Studio" -DCONAN_COMPILER_VERSION="12" -Wno-dev
Error while executing:
         conan test -s compiler="Visual Studio" -s compiler.version=12 -s arch=x86_64 -s build_type=Debug -s compiler.runtime=MDd -o Boost:shared=False
```

**Comment by lasote** [comment]
Yes, sorry. 1.58.0 recipe is a little outdated, my fault. If you need it I can upgrade the recipe to build right. Just tell me if you need it or if you can upgrade to 1.60.0. Thanks!

**Comment by ksmith-mm** [comment]
Thanks for the quick reply! If you do not mind updating the 1.58.0 recipe it would be greatly appreciated. We currently have a large code base using 1.58.0 with with multiple projects linked via SVN externals and I am exploring optimizing our build process by using git, cmake and conan. Upgrading boost as part of this conversion is a bit of a scary thing to do.

**Comment by lasote** [comment]
Hi! I've udpate the recipe for 1.58.0, you should be able to build it from source now. Please, tell me if it works for you.
