### ISSUE TITLE
UnicodeDecodeError when doing a test_package

### ISSUE THREAD

**Issue by dkgs** [lasote/conan-boost#34]
I'm trying to adapt your conanfile.py for being able to have boost in conan for an isolated network. I also modified the conanfile.py in the test package. Both files are attached.

The differences between my version and yours are : 
- the sources are included in the recipe so I don't have to download boost and unzip it;
- I have removed the python and bzip deps;

My configuration is the following : Win7, Visual Studio 10, Conan 1.6.0, Cmake 3.7.0

I get two differents errors depending on the use of short_paths = True or False.
The conan console with short_paths = True : 

> C:\Workspaces\Temp\boost_1_59_0>conan test_package
> Exporting package recipe
> boost/1.59.0@user/channel export: Copied 250 '' files
> boost/1.59.0@user/channel export: Copied 7 '.graffle' files
> [...]
> boost/1.59.0@user/channel export: Copied 1 '.tst2' files: ifstream_line_iterator.tst2
> boost/1.59.0@user/channel export: Copied 1 '.doxyfile' files: windows-paths-check.doxyfile
> boost/1.59.0@user/channel: A new conanfile.py version was exported
> boost/1.59.0@user/channel: Folder: C:\Conan\boost\1.59.0\user\channel\export
> boost/1.59.0@user/channel: Package recipe modified in export, forcing source folder removal
> boost/1.59.0@user/channel: Use the --keep-source, -k option to skip it
> boost/1.59.0@user/channel: Removing 'source' folder, this can take a while for big packages
> boost/1.59.0@user/channel: WARN: [Error 145] Le rpertoire nest pas vide: u'C:/.conan\\xnm6jr\\1'
> WARN: config() has been deprecated. Use config_options and configure
> Requirements
>     boost/1.59.0@user/channel from local
> Packages
>     boost/1.59.0@user/channel:4c07c57fb6551a5dcaf87b7d4f715de1120ade0a
> 
> boost/1.59.0@user/channel: Installing package 4c07c57fb6551a5dcaf87b7d4f715de1120ade0a
> boost/1.59.0@user/channel: WARN: Forced build from source
> boost/1.59.0@user/channel: Building your package in C:/.conan\afinbr\1
> boost/1.59.0@user/channel: WARN: Trying to remove dirty source folder
> boost/1.59.0@user/channel: WARN: This can take a while for big packages
> boost/1.59.0@user/channel: Configuring sources in C:/.conan\xnm6jr\1
> Traceback (most recent call last):
>   File "<string>", line 10, in <module>
>   File "<string>", line 6, in run
>   File "conan\conans\client\command.py", line 930, in main
>   File "conan\conans\client\command.py", line 832, in run
>   File "conan\conans\client\command.py", line 327, in test_package
>   File "conan\conans\client\manager.py", line 295, in install
>   File "conan\conans\client\installer.py", line 60, in install
>   File "conan\conans\client\installer.py", line 145, in _build
>   File "conan\conans\client\installer.py", line 198, in _build_node
>   File "conan\conans\client\installer.py", line 268, in _build_package
>   File "conan\conans\client\source.py", line 41, in config_source
>   File "shutil.py", line 189, in copytree
>   File "shutil.py", line 189, in copytree
>   File "shutil.py", line 189, in copytree
>   File "shutil.py", line 189, in copytree
>   File "shutil.py", line 183, in copytree
>   File "ntpath.py", line 85, in join
> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 12: ordinal not in range(128)
> conan returned -1

With short_paths = False it goes a little further : 

> C:\Workspaces\Temp\boost_1_59_0>conan test_package
> Exporting package recipe
> boost/1.59.0@user/channel export: Copied 250 '' files
> boost/1.59.0@user/channel export: Copied 7 '.graffle' files
> [...]
> boost/1.59.0@user/channel export: Copied 1 '.doxyfile' files: windows-paths-check.doxyfile
> boost/1.59.0@user/channel: A new conanfile.py version was exported
> boost/1.59.0@user/channel: Folder: C:\Conan\boost\1.59.0\user\channel\export
> boost/1.59.0@user/channel: Package recipe modified in export, forcing source folder removal
> boost/1.59.0@user/channel: Use the --keep-source, -k option to skip it
> boost/1.59.0@user/channel: Removing 'source' folder, this can take a while for big packages
> WARN: config() has been deprecated. Use config_options and configure
> Requirements
>     boost/1.59.0@user/channel from local
> Packages
>     boost/1.59.0@user/channel:85f780d0530411a64b0be4407b381706014b445d
> 
> boost/1.59.0@user/channel: Installing package 85f780d0530411a64b0be4407b381706014b445d
> boost/1.59.0@user/channel: WARN: Package doesn't have a remote defined. Probably created locally and not uploaded
> boost/1.59.0@user/channel: Building your package in C:\Conan\boost\1.59.0\user\channel\build\85f780d0530411a64b0be4407b381706014b445d
> boost/1.59.0@user/channel: Configuring sources in C:\Conan\boost\1.59.0\user\channel\source
> boost/1.59.0@user/channel: Copying sources to build folder
> boost/1.59.0@user/channel: WARN: Filename too long, file excluded: C:\Conan\boost\1.59.0\user\channel\build\85f780d0530411a64b0be4407b381706014b445d\libs\geometry\doc\html\geometry\reference\spatial_indexes\boost__geometry__index__rtree\rtree_parameters_type_const____indexable_getter_const____value_equal_const____a
> llocator_type_const___.html
> boost/1.59.0@user/channel: Generated txt created conanbuildinfo.txt
> Building Boost.Build engine
> 
> Bootstrapping is done. To build, run:
> 
>     .\b2
> 
> To adjust configuration, edit 'project-config.jam'.
> Further information:
> 
>     - Command line help:
>     .\b2 --help
> 
>     - Getting started guide:
>     http://boost.org/more/getting_started/windows.html
> 
>     - Boost.Build documentation:
>     http://www.boost.org/build/doc/html/index.html
> boost/1.59.0@user/channel: WARN: b2 toolset=msvc-10.0 link=static runtime-link=shared variant=release address-model=64  -j4
> Performing configuration checks
> 
>     - 32-bit                   : yes
>     - arm                      : no
>     - mips1                    : no
>     - power                    : no
>     - sparc                    : no
>     - x86                      : yes
> 
> Building the Boost C++ Libraries.
> 
> 
>     - symlinks supported       : no
>     - junctions supported      : yes
>     - hardlinks supported      : yes
>     - has_icu builds           : no
> warning: Graph library does not contain MPI-based parallel components.
> note: to enable them, add "using mpi ;" to your user-config.jam
>     - zlib                     : no
>     - iconv (libc)             : no
>     - iconv (separate)         : no
>     - icu                      : no
>     - icu (lib64)              : no
>     - compiler-supports-visibility : no
>     - message-compiler         : yes
>     - compiler-supports-ssse3  : yes
>     - compiler-supports-avx2   : no
>     - gcc visibility           : no
>     - long double support      : yes
> warning: skipping optional Message Passing Interface (MPI) library.
> note: to enable MPI support, add "using mpi ;" to user-config.jam.
> note: to suppress this message, pass "--without-mpi" to bjam.
> note: otherwise, you can safely ignore this message.
> warning: No python installation configured and autoconfiguration
> note: failed.  See http://www.boost.org/libs/python/doc/building.html
> note: for configuration instructions or pass --without-python to
> note: suppress this message and silently skip all Boost.Python targets
> 
> Component configuration:
> 
>     - atomic                   : building
>     - chrono                   : building
>     - container                : building
>     - context                  : building
>     - coroutine                : building
>     - coroutine2               : building
>     - date_time                : building
>     - exception                : building
>     - filesystem               : building
>     - graph                    : building
>     - graph_parallel           : building
>     - iostreams                : building
>     - locale                   : building
>     - log                      : building
>     - math                     : building
>     - mpi                      : building
>     - program_options          : building
>     - python                   : building
>     - random                   : building
>     - regex                    : building
>     - serialization            : building
>     - signals                  : building
>     - system                   : building
>     - test                     : building
>     - thread                   : building
>     - timer                    : building
>     - wave                     : building
> 
> ...patience...
> ...patience...
> ...patience...
> ...patience...
> ...found 11960 targets...
> ...updating 578 targets...
> common.mkdir stage
> [...]
> msvc.archive bin.v2\libs\wave\build\msvc-10.0\release\address-model-64\link-static\threading-multi\libboost_wave-vc100-mt-1_59.lib
> common.copy stage\lib\libboost_wave-vc100-mt-1_59.lib
> bin.v2\libs\wave\build\msvc-10.0\release\address-model-64\link-static\threading-multi\libboost_wave-vc100-mt-1_59.lib
>         1 fichier(s) copié(s).
> ...updated 578 targets...
> 
> 
> The Boost C++ Libraries were successfully built!
> 
> The following directory should be added to compiler include paths:
> 
>     C:\Conan\boost\1.59.0\user\channel\build\85f780d0530411a64b0be4407b381706014b445d
> 
> The following directory should be added to linker library paths:
> 
>     C:\Conan\boost\1.59.0\user\channel\build\85f780d0530411a64b0be4407b381706014b445d\stage\lib
> 
> 
> boost/1.59.0@user/channel: Package '85f780d0530411a64b0be4407b381706014b445d' built
> boost/1.59.0@user/channel: Build folder C:\Conan\boost\1.59.0\user\channel\build\85f780d0530411a64b0be4407b381706014b445d
> Traceback (most recent call last):
>   File "<string>", line 10, in <module>
>   File "<string>", line 6, in run
>   File "conan\conans\client\command.py", line 930, in main
>   File "conan\conans\client\command.py", line 832, in run
>   File "conan\conans\client\command.py", line 327, in test_package
>   File "conan\conans\client\manager.py", line 295, in install
>   File "conan\conans\client\installer.py", line 60, in install
>   File "conan\conans\client\installer.py", line 145, in _build
>   File "conan\conans\client\installer.py", line 201, in _build_node
>   File "conan\conans\model\manifest.py", line 28, in summary_hash
>   File "conan\conans\util\files.py", line 41, in md5
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 3040070: ordinal not in range(128)
> conan returned -1

Any idea of what could cause the issue ? From what I understand some characters in paths are not well treated either for copying the sources or computing the hash.

If this has nothing to do with the conanfile.py itself I would gladly transfer this issue in the conan repo :)

[conanfile.py.txt](https://github.com/lasote/conan-boost/files/638722/conanfile.py.txt)
[conanfile_test.py.txt](https://github.com/lasote/conan-boost/files/638723/conanfile_test.py.txt)

**Comment by dkgs** [comment]
Some more info : 
- When I do a `conan build`, it works fine
- When I do a `cd mypackage && conan package ..` works fine too

**Comment by dkgs** [comment]
I mixed up the conan version & the boost version :
 - I had two conan versions installed and the 1.6.0 was taking over the 1.6.1 (due to my %PATH%).
 - I used your conanfile.py for boost 1.60.0 whereas I was manipulating boost 1.59.0 and moreover keeping boost sources in a zip file ease the use as conan don't have to copy each file in the local store (had a problem with long path name when copying into the local store).

Everything works fine from my side now.

You can close this issue.

**Comment by lasote** [comment]
Thanks, yeah, the recipe from 1.59.0 is a little outdated and could have issues already fixed in 1.60
If you used 1.60 to create a 1.59 recipe just be careful with the library list declared in the `package_info` method. They change between those versions.
