### ISSUE TITLE
Visual Studio 14 x86 Debug - Boost libraries not found

### ISSUE THREAD

**Issue by jgsogo** [lasote/conan-boost#36]
I have a dependency on ``boost/1.60@lasote/stable`` and my CI appveyor is failing to compile for the following toolchain: **Visual Studio 14 x86 Debug**. Here your have the [last job](https://ci.appveyor.com/project/jgsogo/queryset-cpp) where it passed for other compiler, versions and options, but fails for this concrete one.

It seems that there is a missing file: ``FindBoost.cmake`` in the conan package, and the ``OriginalFindBoost...`` ones.

**Comment by lasote** [comment]
Hi @jgsogo. I'll check it later ok? thanks for reporting. I hope you have your pretty build green very soon! :+1:

**Comment by lasote** [comment]
Try now please! I've uploaded a new package for that settings.

**Comment by jgsogo** [comment]
Job rescheduled! Let's see what happens

**Comment by jgsogo** [comment]
You did it! :perf:

**Comment by lasote** [comment]
Feliz Navidad!

**Comment by jgsogo** [comment]
Muchas gracias. Igualmente, ¡Felices Fiestas!
