### ISSUE TITLE
Exclude component from libs based on without_ options

### ISSUE THREAD

**Issue by theirix** [lasote/conan-boost#39]
If I use any of without_foo options, an `foo` component is properly excluded from the build but stays in libs and in CONAN_LIBS. It causes a linking error for the app.
For example `ld: library not found for -lboost_wave` for the option `Boost:without_wave=True`. Checked for `Boost/1.60.0@lasote/stable`.

**Comment by sixten-hilborn** [comment]
I've experienced this issue too, just submitted a PR: #40.
