### ISSUE TITLE
zlib and bzip2 are not linked

### ISSUE THREAD

**Issue by theirix** [lasote/conan-boost#42]
Boost iostreams is not linked to dependencies zlib and bzip2 that are always specified with the Boost's conanfile. Recipe for 1.60.0 explicitly links to bzip2 using `include_path`, `lib_path` (see `prepare_deps_options`) but not zlib and 1.62.0 does not specify any of them. So only system dependencies at `/usr` are used if present.

Checked with a clean Fedora without zlib and bzip2 packages installed. Also it can be seen for travis jobs for [boost 1.60.0](https://travis-ci.org/lasote/conan-boost/jobs/201054694#L2385) and [boost 1.62.0](https://travis-ci.org/lasote/conan-boost/jobs/183201707#L541).

**Comment by lasote** [comment]
Please, take a look to the testing/1.64.0 branch and let me know if it's working now.

**Comment by lasote** [comment]
It seems to work in Linux and OSX, at least the paths passed to the compiler are correct but in Windows it's ignored. The new recipe: https://github.com/lasote/conan-boost/blob/testing/1.64.0/conanfile.py

**Comment by lasote** [comment]
The windows case has been patched too. Replacing "\" with "/". Only 1.64.0 branch is going to be updated.

**Comment by theirix** [comment]
Sorry, missed a notification for this ticket. Cannot fully reproduce due to #51. Accordingly to b2 configs it is fixed now, thank you.
