### ISSUE TITLE
*FindBoost*.cmake are missing on header_only package.

### ISSUE THREAD

**Issue by bilke** [lasote/conan-boost#45]
The following files are missing on the current Boost 1.60.0 (5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9) `header_only`-package:

- `FindBoost.cmake`
- `OriginalFindBoost_3_0_2.cmake`
- `OriginalFindBoost_3_4_3.cmake`

**Comment by lasote** [comment]
Hi! I've uploaded the header only package containing those files, but I'm little surprised about the SHA1 of the package. The SHA1 of the header only package is `524ea35a8120baabdde02483add58d81bf541327` do you have the latest recipe?
