### ISSUE TITLE
Add build for Linux/Clang

### ISSUE THREAD

**Issue by mcraveiro** [lasote/conan-boost#5]
Hi @lasote 

As discussed[1], is it possible to add support for boost on Linux/Clang? 

Many thanks for your time.

Marco

[1] https://github.com/conan-io/conan/issues/138#issuecomment-198434239

**Comment by Manu343726** [comment]
+1 https://travis-ci.org/GueimUCM/siplasplas/jobs/122767845

**Comment by lasote** [comment]
I added the 1.66.0 recipe, it should work well.
