### ISSUE TITLE
Cannot seem to specify any option

### ISSUE THREAD

**Issue by JPGygax68** [lasote/conan-boost#50]
I'm getting
```
ERROR: boost/1.62.0@lasote/vcpkg: 'options.shared' doesn't exist
Possible options are []
```

when I try to install my my dependencies (command is `conan install ..`, from the build subdirectory). 
I've simplified my conanfile to this:
```
[requires]
zlib/1.2.11@lasote/stable
boost/1.62.0@lasote/vcpkg

[options]
zlib:shared=False
boost:shared=False
```

(I've added zlib to compare behaviours.) The zlib recipe accepts the option, boost doesn't.
For completeness, here's my default profile:
```
[build_requires]
[settings]
os=Windows
arch=x86_64
compiler=Visual Studio
compiler.version=14
compiler.runtime=MD
build_type=Release
[options]
[scopes]
[env]
```
However there should be nothing special about it since I had deleted the user `.conan` directory and let conan re-create it.

**Comment by lasote** [comment]
Forget the `lasote/vcpkg` package, is an automatic scraped package from the vcpkg package manager. It's not tested not maintained. Sorry

**Comment by JPGygax68** [comment]
Ah, I was wondering where the `vcpkg` came from. Thanks for explaining.
