### ISSUE TITLE
Build fails on CentOS 7.3

### ISSUE THREAD

**Issue by amues** [lasote/conan-boost#51]
When trying to install the package on CentOS 7.3, using a clean _centos_ Docker image with only build tools and Conan installed, no options specified, I got the following error:
```
ERROR: Boost/1.64.0@conan/stable: Error in build() method, line 254
	self.run(full_command)
	ConanException: Error 256 while executing cd boost_1_64_0 && ./b2 toolset=gcc-4.8 link=static variant=release address-model=64 define=_GLIBCXX_USE_CXX11_ABI=0  -j4 --abbreviate-paths --without-python -d2
```

If I run the command
```
./b2 toolset=gcc-4.8 link=static variant=release address-model=64 define=_GLIBCXX_USE_CXX11_ABI=0  -j4 --abbreviate-paths --without-python -d2
```
from the _build/<sha>/boost_1_64_0_ folder, I get
```
error: duplicate initialization of gcc with the following parameters: 
error: version = 4.8.5
error: previous initialization at project-config.jam:12
```
It seems to work if I run the command without `toolset=gcc-4.8`, though.

**Comment by miqelm** [comment]
There is specified gcc version with option toolset to be 4.8, but detected by bootstrap is 4.8.5. Due to this mismatch there is error.

@lasote Maybe there should be specifying toolset option to b2 not gcc-version (which conan resolved ignoring patch number_), but only gcc?

**Comment by theirix** [comment]
Similar issue while installing Boost on Fedora 25 using

```
conan install --build=missing Boost/1.64.0@conan/stable
```

Compilers:
```
# yum list installed | grep gcc
gcc.x86_64                          6.4.1-1.fc25                @updates
gcc-c++.x86_64                      6.4.1-1.fc25                @updates
```

Error:
```
Boost/1.64.0@conan/stable: WARN: Patching project-config.jam
Boost/1.64.0@conan/stable: WARN: cd boost_1_64_0 && ./b2 toolset=gcc-6 link=static variant=release address-model=64 define=_GLIBCXX_USE_CXX11_ABI=0  -j4 --abbreviate-paths --without-python -d2
/root/.conan/data/Boost/1.64.0/conan/stable/build/e401890ac44ea33209c3fdeab3f6787fc00fbdcc/boost_1_64_0/tools/build/src/tools/gcc.jam:123: in gcc.init from module gcc
error: toolset gcc initialization:
error: version '6' requested but 'g++-6' not found and version '6.4.1' of default 'g++' does not match
error: initialized from
/root/.conan/data/Boost/1.64.0/conan/stable/build/e401890ac44ea33209c3fdeab3f6787fc00fbdcc/boost_1_64_0/tools/build/src/build/toolset.jam:43: in toolset.using from module toolset
/root/.conan/data/Boost/1.64.0/conan/stable/build/e401890ac44ea33209c3fdeab3f6787fc00fbdcc/boost_1_64_0/tools/build/src/build-system.jam:461: in process-explicit-toolset-requests from module build-system
/root/.conan/data/Boost/1.64.0/conan/stable/build/e401890ac44ea33209c3fdeab3f6787fc00fbdcc/boost_1_64_0/tools/build/src/build-system.jam:527: in load from module build-system
/root/.conan/data/Boost/1.64.0/conan/stable/build/e401890ac44ea33209c3fdeab3f6787fc00fbdcc/boost_1_64_0/tools/build/src/kernel/modules.jam:295: in import from module modules
/root/.conan/data/Boost/1.64.0/conan/stable/build/e401890ac44ea33209c3fdeab3f6787fc00fbdcc/boost_1_64_0/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/root/.conan/data/Boost/1.64.0/conan/stable/build/e401890ac44ea33209c3fdeab3f6787fc00fbdcc/boost_1_64_0/boost-build.jam:17: in module scope from module
```

**Comment by helmesjo** [comment]
What was the conclusion on this? I get the same error as @theirix :
`version '6' requested but 'g++-6' not found and version '6.4.0' of default 'g++' does not match`

**Comment by theirix** [comment]
I think the best way is to provide an option to override `toolset` value and it will solve all problems.
For example, compilers from RHEL devtoolset-4 are identified as `gcc` although they are of version 6.

**Comment by lasote** [comment]
Hi all! this problem should be fixed in the new 1.66.0 recipe. Could you try it and report? Thanks!

**Comment by theirix** [comment]
Works fine with Fedora 25 with gcc 6.4 (toolset "gcc 6"):
<code>
 /root/.conan/data/Boost/1.66.0/conan/stable/build/1746e628e6a5e266b0a8c605d6751b6251f94e10/boost_1_66_0/tools/build/b2 --layout=system toolset=gcc-6 link=static variant=release address-model=64 --without-python define=_GLIBCXX_USE_CXX11_ABI=0  -j4 --abbreviate-paths -d2 --debug-configuration --build-dir="/root/.conan/data/Boost/1.66.0/conan/stable/build/1746e628e6a5e266b0a8c605d6751b6251f94e10"
</code>

And with centos 7.3 using standard gcc compiler:
<code>
Boost/1.66.0@conan/stable: Using gcc 4.8
Bootstrapping the build engine with toolset gcc... engine/bin.linuxx86_64/b2
...
using gcc : 4.8 : "/usr/bin/gcc" ;
Boost/1.66.0@conan/stable: WARN: /root/.conan/data/Boost/1.66.0/conan/stable/build/2d03252301f0f87015265771f29a98117806276a/boost_1_66_0/tools/build/b2 --layout=system toolset=gcc-4.8 link=static variant=release address-model=64 --without-python define=_GLIBCXX_USE_CXX11_ABI=0  -j4 --abbreviate-paths -d2 --debug-configuration --build-dir="/root/.conan/data/Boost/1.66.0/conan/stable/build/2d03252301f0f87015265771f29a98117806276a"
</code>

**Comment by theirix** [comment]
Confirmed it was working even on centos 6 with devtoolset-4 using [those containers](https://github.com/theirix/docker-conantest).

**Comment by amues** [comment]
Builds fine on CentOS 7.4 with the standard GCC as well. Thank you!
