### ISSUE TITLE
header_only=True adds bzip2 and zlib dependency

### ISSUE THREAD

**Issue by bilke** [lasote/conan-boost#52]
Is it indented that `header_only=True` adds a `bzip2` and `zlib` dependency?

I want to remove the dependency. Adding `Boost:without_iostreams=True` works but there is no prebuilt package available (because all options are stripped when the `header_only` package is built) although it should be identical to the `header_only`-package.

**Comment by lasote** [comment]
Would be great if you can help with a PR, maintaining myself several packages is too hard.

**Comment by bilke** [comment]
Will submit a PR!
