### ISSUE TITLE
Static lib names are wrong on Windows VS

### ISSUE THREAD

**Issue by Brunni** [lasote/conan-boost#54]
I have tested boost "Boost/1.64.0@conan/stable".
Package id is: ee5dab950b6ea94ae953b93c55343e98c2ec39df

Building for Visual Studio on Windows:

The static lib names are prefixed with "lib" but shouldn't be:
In VS config I have:
```
libboost_wave-vc140-mt-1_64.lib
libboost_unit_test_framework-vc140-mt-1_64.lib
libboost_prg_exec_monitor-vc140-mt-1_64.lib
libboost_container-vc140-mt-1_64.lib
libboost_graph-vc140-mt-1_64.lib
libboost_iostreams-vc140-mt-1_64.lib
libboost_locale-vc140-mt-1_64.lib
libboost_log-vc140-mt-1_64.lib
libboost_log_setup-vc140-mt-1_64.lib
libboost_math_c99-vc140-mt-1_64.lib
libboost_math_c99f-vc140-mt-1_64.lib
libboost_math_c99l-vc140-mt-1_64.lib
libboost_math_tr1-vc140-mt-1_64.lib
libboost_math_tr1f-vc140-mt-1_64.lib
libboost_math_tr1l-vc140-mt-1_64.lib
libboost_program_options-vc140-mt-1_64.lib
libboost_random-vc140-mt-1_64.lib
libboost_regex-vc140-mt-1_64.lib
libboost_wserialization-vc140-mt-1_64.lib
libboost_serialization-vc140-mt-1_64.lib
libboost_signals-vc140-mt-1_64.lib
libboost_coroutine-vc140-mt-1_64.lib
libboost_context-vc140-mt-1_64.lib
libboost_timer-vc140-mt-1_64.lib
libboost_thread-vc140-mt-1_64.lib
libboost_chrono-vc140-mt-1_64.lib
libboost_date_time-vc140-mt-1_64.lib
libboost_atomic-vc140-mt-1_64.lib
libboost_filesystem-vc140-mt-1_64.lib
libboost_system-vc140-mt-1_64.lib
libboost_exception-vc140-mt-1_64.lib
```
On my computer it is without the lib prefix.

I guess this is the problem:
`prefix = "lib" if not self.options.shared else ""`

Regards
Michael

**Comment by lasote** [comment]
But the real file name is with or without the "lib" prefix? I mean, it's a bug in the `package_info()` or it works?

**Comment by Brunni** [comment]
The real files don't have the lib prefix. See the tgz from here:
https://bintray.com/conan-community/conan/Boost%3Aconan#files/conan%2FBoost%2F1.64.0%2Fstable%2Fpackage%2Fc4aef4edbc33205e0cf9b55bfb116b38c90ec132

**Comment by lasote** [comment]
You are right, I was only using the CMake find_package to reuse the packages and I didn't realize that the CONAN_LIBS was incorrect. 
I've pushed the changes with some new improvement to set the correct environment for visual studio. Let's see how it goes in the CI servers

**Comment by Brunni** [comment]
Thank you very much. I was also wondering how test_package could succeed...

**Comment by lasote** [comment]
Pushed to release branch, the packages of bintray will be updated in some hours.

**Comment by Brunni** [comment]
I think this is not working as expected somehow.

In https://stackoverflow.com/a/35607887 someone is stating, that the static dlls are expected to have the lib prefix. And the lib file for dynamic libraries don't. I cannot tell if this is correct.

But I'm currently having the following issue:
- In one of my project everything seems to work fine now.
- In the other project linking fails with `cannot open file 'libboost_date_time-vc140-mt-1_64.lib'` althought I couldn't find any reference on "libboost" in configurations.

It seems that some boost library is depending on the 'libboost_date_time' library and therefore it fails.

**Comment by lasote** [comment]
Irrespective of the name that the libraries have, if the name of the library to link with is correct it should work. Please, give me some details about how are you linking with Boost in the example where you are getting the `cannot open file 'libboost_date_time-vc140-mt-1_64.lib`.
Are you using conan? Are you using conan-boost package? Which version? from which repository?

Thanks

**Comment by Brunni** [comment]
I just realized, that it might be somehow my problem... It is a really strange project setup, and I guess that the libs that we use there are already depending on libboost somehow... and therefore they expect the file to be exactly named like this...
