### ISSUE TITLE
Build boost 1.57.0 with zlib and bzip2 present on Conan

### ISSUE THREAD

**Issue by Israphel** [lasote/conan-boost#56]
I have bzip2 and zlib on my Conan repo and cache, I'd like to use them to build boost. I added the "requires" line in conanfile.py and conan install worked fine, but stil the build process indicates "zlib no" and then it fails because of bzip2.
I see that you do that for the 1.64.0 recipe. Can't we do the same for this version? Thanks.

**Comment by lasote** [comment]
I think it should be fixed in the 1.66.0 recipe, please take a look and report if it still fail. Thanks and sorry for the delay, we have been extremely busy with the Conan 1.0 release.
