### ISSUE TITLE
Linking error when building without-test

### ISSUE THREAD

**Issue by Toinouze** [lasote/conan-boost#59]
Hi,

conan-boost has options to use Boost without some libs, like Boost's unit testing framework.

conanfile.txt : 
```
[requires]
Boost/1.64.0@conan/stable

[options]
Boost:shared=False
Boost:without_test=True

[generators]
cmake
```
The result is linking errors : 
```
Undefined symbols for architecture x86_64:
  "init_unit_test_suite(int, char**)", referenced from:
      _main in libboost_unit_test_framework.a(unit_test_main.o)
```
The problem is that Conan doesn't remove those libs from the generated CONAN_LIBS variable.
In the conanbuildinfo.cmake : 
```
set(CONAN_LIBS_BOOST boost_atomic boost_chrono boost_container boost_context 
boost_coroutine boost_date_time boost_exception boost_fiber boost_filesystem boost_graph 
boost_iostreams boost_locale boost_log boost_log_setup boost_math_c99 
boost_math_c99f boost_math_c99l boost_math_tr1 boost_math_tr1f 
boost_math_tr1l boost_program_options boost_random boost_regex 
boost_serialization boost_signals boost_system boost_thread boost_timer 
boost_type_erasure /* HERE */ boost_unit_test_framework boost_wave boost_wserialization)
```
My workaround is to manually remove unwanted libs in CMakeLists.txt, but it's ugly :  
```
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
list(REMOVE_ITEM CONAN_LIBS boost_unit_test_framework)
```
Is there a better way ?

Thanks

**Comment by lasote** [comment]
That's weird, we are using the ``self.collect_libs()`` in the ``package_info`` method, so why is Boost generating the ``boost_unit_test_framework`` library even with the option ``--without_test``?

**Comment by lasote** [comment]
Anyway, I've pushed a patch to the recipe, the CI would be some time generating packages but the recipe should be updated soon, so perform an install with ``--update`` and it should work now.

**Comment by lasote** [comment]
Feel free to write again if it's not fixed yet.
Thanks for reporting.

**Comment by Toinouze** [comment]
It works. Thanks !
