### ISSUE TITLE
Provide a source-only package

### ISSUE THREAD

**Issue by bilke** [lasote/conan-boost#6]
Lots of Boost libraries are header-only and can therefore be used without building anything. It would be nice if there would be an option on this package to just download the header-files of the header-only libs.

**Comment by lasote** [comment]
Hi! I've uploaded the recipe with a new option "header_only". This recipe removes all settings if "header_only" option is activated, so there is only one header only package for all the possibles settings combinations. Could you try it?

conan install -o header_only=True

**Comment by bilke** [comment]
Thanks! Because the package was not yet available from `conan.io` I had to build it locally with `conan install -o header_only=True --build Boost` but everything worked fine!

**Comment by lasote** [comment]
Mhh, I've uploaded the package... something may be failing. Do you have the SHA (ugly package reference) of the build package?

**Comment by bilke** [comment]
It should be `c48a91e2baac19d1ec92ed2b815f2406b906deb3`

**Comment by lasote** [comment]
Thanks! It's all ok! I'm working in a new recipe that removes the shared option from package when header_only is activated, so only the c48a91e2baac19d1ec92ed2b815f2406b906deb3 package will exists. My package was different because I specified shared=True but it has no sense. Thanks bilke!

**Comment by lasote** [comment]
PD: package c48a91e2baac19d1ec92ed2b815f2406b906deb3 is now uploaded too.Pending some checks to upload the new recipe that exclude the shared option

**Comment by bilke** [comment]
The uploaded package is basically empty (just containing FindBoost.cmake, conaninfo.txt, conanmanifest.txt)

**Comment by lasote** [comment]
You are right. Sorry, it is uploaded now ok.

**Comment by bilke** [comment]
Thanks!

**Comment by bilke** [comment]
One more question: I am trying to use this package again on Windows but it tries to download this package: `04543718a52b42cc8a50670c07ecea0ee3ddd963` (which does not exist). For package configuration it prints: `Options: header_only=True, zlib:shared=False`.

**Comment by lasote** [comment]
Yes, it changes because in windows the require to bzip2 doesn't exists. Thanks for notice it.
I'm uploading the package in few minutes.

**Comment by lasote** [comment]
Sorry, we have discovered a bug related with this thing and sha's compute. Try to use --build until we find a solution.

Thanks!

**Comment by lasote** [comment]
Could you try now using install -u ?

**Comment by bilke** [comment]
Thanks it works!

**Comment by lasote** [comment]
:+1:
