### ISSUE TITLE
requires zlib is too selective

### ISSUE THREAD

**Issue by kmaragon** [lasote/conan-boost#60]
patch_project_jam uses bzip2 and zlib via the requirements. But neither of these are enabled if without_iostreams is set or if header_only is set. Thus the package is entirely incapable of building if either of these flags is `True`

**Comment by lasote** [comment]
Probably this issue is still present in the 1.66.0 recipe, if you could take a look and open a PR would be great.

**Comment by KalleDK** [comment]
Does all the modules require bzip2 and zlib or is it only iostreams ?

**Comment by KalleDK** [comment]
Added #72 to remove the io_stream check  - tested by only building system and the rest put to True (not header only ofcourse)

**Comment by KalleDK** [comment]
@lasote think you can close this now then 👍
