### ISSUE TITLE
static links fail non-deterministically

### ISSUE THREAD

**Issue by kmaragon** [lasote/conan-boost#62]
Admittedly, this issue might be better suited for the conan project itself. conan-boost uses tools.collect_libs to get the library list. It seems like the implementation of that just collects the libraries in directory order. The problem is that while statically linking the libraries, at least on *nix systems, the link order very much matters. And the order of the list that collect_libs produces is the order that libraries are linked in the link command from at least CMake. I discovered this while statically linking against boost_coroutine which then uses boost_context. This package set up the cpp_info.libs (based on collect_libs) such that context came before coroutine. The glibc linker needs them in reverse dependency order. As a result, the build fails and I can't use the libraries generated by the package without manually doctoring the generated cmake file or generated conan metadata. When I do that and put boost_context *after* boost_coroutine, everything compiles fine. But it'd be nice if the package would just deterministically work rather than depend on the OS to hopefully write the files in reverse dependency order in the build output directory.

**Comment by kmaragon** [comment]
In reality, the boost package probably needs some kind of internal dependency database anyway. Related to this, I can add options that have "without_coroutine=False","without_context=True" and I'll just be producing a boost setup that can't compile at all. So to predictably produce good libraries, the package probably needs to know that one option requires the other.  As such, it could then know that one library or collection of libraries depends on the other and build the cpp_info.libs accordingly.

On the other hand, build tools like cmake handle this already. If each of the boost modules is turned into its own package. And then conan takes care of the dependencies and such without needing a bunch of python code to rebuild the same thing that all of these other tools already do.

**Comment by lasote** [comment]
Hi, you are right. I created a new recipe for 1.66.0 and I took into account the library order. Please, review it and feel free to open a PR. I made many many changes to the 1.66.0 recipe, so I would like to go with it instead of support the 1.65.1. Sorry for the delay, we were very busy with the 1.0 release.
Thanks for your help!
