### ISSUE TITLE
Unable to successfully cross-compile for ARM

### ISSUE THREAD

**Issue by DavidZemon** [lasote/conan-boost#65]
Trying to link against boost that has been "cross-compiled" for ARM results in this error:

```
/home/developer/.conan/data/Boost/1.64.0/conan/stable/package/8958ea8fe46c6a287cfebd83c229c8fbd67e037e/lib/libboost_program_options.a: error adding symbols: File format not recognized
collect2: error: ld returned 1 exit status
```

Which makes sense given the fact that one of the compilation lines for a boost source file looks like this:

```
"g++-4.9"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -pthread -m64 -ftemplate-depth-255 -fvisibility=hidden -fvisibility-inlines-hidden -DBOOST_ALL_NO_LIB=1 -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=0  -I"." -c -o "bin.v2/libs/serialization/build/gcc-4.9/rls/lnk-sttc/thrd-mlt/text_wiarchive.o" "libs/serialization/src/text_wiarchive.cpp"
```

Of particular interest is the `-m64`, indicating that Boost.Build thinks it is building for x86-64, not ARM. The Conan profile used is as follows:

```
[build_requires]
[settings]
os=Linux
arch=armv7hf
compiler=gcc
compiler.version=4.9
compiler.libcxx=libstdc++
build_type=Release
[options]
[env]
```

**Comment by lasote** [comment]
I updated the 1.66.0 recipe and tested the cross compilation to ARM successfully.

**Comment by lasote** [comment]
Please, try it and feel free to write again if any problem. Thanks for your help. I added a mention in the readme.
