### ISSUE TITLE
boost 1.66 does not build with conan < 0.99

### ISSUE THREAD

**Issue by sturmf** [lasote/conan-boost#67]
The conanfile.py in testing/1.66.0 suggests that it still works with conan < 0.99 but the bootstrap method tries to use the self.settings.os_build which does not exist.

I know one fix would be to upgrade my conan version, but this takes a while :-)

**Comment by lasote** [comment]
I'm working on the recipe but I'm definitely using Conan 1.0 features 😭

**Comment by sturmf** [comment]
Hmm that's ok, for now I have a working recipe and next step is probably to upgrade everyone to use the latest conan version. Even though I saw you dropping the os_build in favor of the plain os variable. Which was my problem here, but I guess at the same time you are introducing other 1.0 dependencies.

**Comment by lasote** [comment]
Yes, we drop the plans to use `os_build` for regular recipes, these settings are only intended to cross builders as build_requires. The cross building support will be improved in Conan > 1.2 probably.

**Comment by lasote** [comment]
By the way, my testing branch is still totally broken for 1.66!

**Comment by lasote** [comment]
I created the release/1.66.0, but using Conan 1.0 features. I have no plans to keep compatibility with Conan < 1.0 features. Sorry.
