### ISSUE TITLE
boost 1.66.0 conanfile configure step sets bzip2 option wrong

### ISSUE THREAD

**Issue by sturmf** [lasote/conan-boost#68]
Hi, I think the following line in the boost 1.66.0 configure method is wrong:

    self.options["bzip2/1.0.6"].shared = self.options.shared

It should be:

    self.options["bzip2"].shared = self.options.shared

Unfortunately bzip2 still can't be built as shared lib under all platforms so for now I think it makes more sense to set it explicitly.

    self.options["bzip2"].shared = False

**Comment by lasote** [comment]
Fixed
