### ISSUE TITLE
boost 1.66.0 zlib name wrong on Linux

### ISSUE THREAD

**Issue by sturmf** [lasote/conan-boost#69]
For me to build boost 1.66.0 against zlib I had to patch the bootstrap flag from:

            flags.append("-sZLIB_BINARY=zlib%s" % ("d" if self.settings.build_type == "Debug" else ""))
 to

            if self.settings.os == "Windows":
                flags.append("-sZLIB_BINARY=zlib%s" % ("d" if self.settings.build_type == "Debug" else ""))
            else:
                flags.append("-sZLIB_BINARY=z")

Otherwise the build passes but does not use the zlib implementation.

**Comment by lasote** [comment]
I'm working right now on the 1.66 recipe. Probably is a good idea to get the lib name from the deps_cpp_info also. I'll try.

**Comment by lasote** [comment]
Fixed
