### ISSUE TITLE
gcc autodetect fails on Fedora

### ISSUE THREAD

**Issue by theirix** [lasote/conan-boost#75]
Reproduced #51 again.

Clarified summary: using only major version in `user-config.jam` (like `using "gcc": "6"`) works only if a Linux distro has a `gcc-6` executable alongside with `gcc`. Otherwise `b2` fails.

It works on Debian and Ubuntu which are used for CI builds. For Debian `gcc-6` is picked up by `b2`. 

But for Fedora (24, 25) only `gcc` binary is here and the `gcc-6` is omitted. So the `b2` fails to find a toolset:
```
warning: toolset gcc initialization: can not find tool g++-6
error: toolset gcc initialization:
error: version '6' requested but 'g++-6' not found and version '6.3.1' of default 'g++' does not match
```

It does not even matter what is it in `settings.compiler.version` - a major version or major.minor version. Now the code checks only the major version and writes it to the `user-config.jam`.

Finally, it works for CentOS 7 because it has gcc 4.8 that is less than 5.

Using `6.3` in a `user-config.jam` works too but it requires a recipe change. The only way to fix a release/1.66.0 without recipe change is to specify `CXX` env var with a path to the actual gcc executable. It would be much better if boost can be built for Fedora.

**Comment by lasote** [comment]
Sorry for the regression, I will look for a fix without hacks. Thanks sooo much

**Comment by lasote** [comment]
Fixed, I tested in a docker container with fedora 25. Please confirm that it's ok, pushed to release/1.66.0. The CI will take some hours to update all the packages and recipes

**Comment by theirix** [comment]
Works perfectly, thanks!
