### ISSUE TITLE
Static library build on Linux is not usable when linking into shared library

### ISSUE THREAD

**Issue by sstone1** [lasote/conan-boost#8]
I'm trying to build a shared library that statically links against Boost on Linux/x86-64.
The Boost static library installed by Conan is not built with -fPIC, so if you attempt to link it into a shared library, you get the following errors:

`/usr/bin/ld: /home/sstone1/.conan/data/Boost/1.60.0/lasote/stable/package/c3a56c4bf2a9bda70840087b704cce268a830898/lib/libboost_system.a(error_code.o): relocation R_X86_64_32 against ``.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/home/sstone1/.conan/data/Boost/1.60.0/lasote/stable/package/c3a56c4bf2a9bda70840087b704cce268a830898/lib/libboost_system.a: error adding symbols: Bad value`

It would be great if an option could be added to the conanfile.py to add -fPIC to cxxflags for the static library build. It looks like the zlib build always adds the -fPIC flag. Mac OS X has -fPIC enabled by default, so the option would only be required for Linux.

**Comment by lasote** [comment]
Could you try with Boost/1.60.0@lasote/ci? Specify the option with "-o Boost:fPIC=True"

**Comment by sstone1** [comment]
@lasote just tried it and it works perfectly, thanks a lot!

**Comment by lasote** [comment]
@sstone1 great, I'll improve some details and publish to stable channel in the following hours. 

Thanks!

**Comment by helmesjo** [comment]
@lasote 
Could you by any chance change `fPIC` default to be `True`? This would address my (and demonstrably others) unnecessary issue when linking `conan-boost` to a shared library. Also, since `fPIC` currently is `False` by default there is a lot of [missing prebuilt packages](https://github.com/conan-community/conan-boost/issues/125) when specifying `boost:fPIC=True` (`fPIC` is a requirement when building shared libs, so there is that also).

**Comment by lasote** [comment]
Yes, probably we should change the default to be consistent with the most conan packages in conan center.

**Comment by helmesjo** [comment]
I created PRs for [1.66.0](https://github.com/conan-community/conan-boost/pull/128) & [1.67.0](https://github.com/conan-community/conan-boost/pull/129).
